version: '2'
services:
  first:
    build: ./first/
    volumes:
      - data_volume:/home/
    networks:
      default:
        aliases:
          - first
  second:
    build: ./second/
    depends_on:
      - first
    volumes:
      - data_volume:/home/
    volumes_from:
      - first
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - second
volumes:
  data_volume:
networks:
  default:
